name = "fizzyhex/revy-game"
version = "0.1.0"
description = ""
authors = ["fizzyhex"]
repository = "https://github.com/Fizzyhex/rbx-revy-template"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.6.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
revy = { name = "fizzyhex/revy", version = "0.11.3" }