std = "selene_definitions+roblox"

[config]
# Allow for `_G.__DEV__` (etc) with packages like React-lua
global_usage = { ignore_pattern = "^__" }

[rules]
global_usage = "allow"
incorrect_standard_library_use = "allow"